/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-fixed-variant": "#2f3aa3",
                "on-surface": "#141d21",
                "surface-container-high": "#e0e9ef",
                "on-tertiary": "#ffffff",
                "tertiary-fixed-dim": "#dcb8ff",
                "surface-tint": "#3c55bf",
                "on-error": "#ffffff",
                "on-primary-fixed": "#001356",
                "secondary-container": "#8792fe",
                "primary-container": "#546cd7",
                "on-tertiary-fixed-variant": "#5c3187",
                "surface-dim": "#d2dbe1",
                "error": "#ba1a1a",
                "on-surface-variant": "#444653",
                "on-secondary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed": "#e0e0ff",
                "outline": "#757684",
                "surface-container": "#e6eff5",
                "surface": "#f4faff",
                "surface-variant": "#dbe4ea",
                "inverse-on-surface": "#e9f2f8",
                "on-tertiary-fixed": "#2c0051",
                "error-container": "#ffdad6",
                "on-secondary-container": "#17228f",
                "primary-fixed": "#dde1ff",
                "background": "#f4faff",
                "on-error-container": "#93000a",
                "tertiary-container": "#8c61b9",
                "on-primary-container": "#fffbff",
                "outline-variant": "#c5c5d5",
                "primary-fixed-dim": "#b9c3ff",
                "on-primary": "#ffffff",
                "surface-container-low": "#ecf5fb",
                "on-primary-fixed-variant": "#1f3ba6",
                "secondary-fixed-dim": "#bdc2ff",
                "tertiary": "#72489e",
                "primary": "#3953bd",
                "inverse-surface": "#293236",
                "tertiary-fixed": "#f0dbff",
                "on-tertiary-container": "#fffbff",
                "on-secondary-fixed": "#000767",
                "surface-bright": "#f4faff",
                "on-background": "#141d21",
                "inverse-primary": "#b9c3ff",
                "secondary": "#4953bc",
                "surface-container-highest": "#dbe4ea"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "sans": ["Inter", "sans-serif"],
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "sm": "0.5rem",
                "md": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
        },
    },
    plugins: [],
}
